REM $Version 1.00 
REM $VersionDate 11.07.2022 
REM $Author YANISHEN_SV
SET TERMOUT  ON
SET ECHO     OFF
SET FEEDBACK ON
SET VERIFY   ON
SET PAUSE    OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE
SET SQLBLANKLINES ON
SPOOL XXWORD.log

PROMPT PRE_INSTALL

SPOOL OFF
EXIT